[package]
name = "radix"
version = "0.1.0"
authors = ["Izumi Raine <63145238+IzumiRaine@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
